create table sensors (
    id integer generated by default as identity primary key,
    name varchar(30) not null unique,
    constraint sensors_name_length_check check (char_length(name) between 3 and 30)
);

create table measurements (
    id integer generated by default as identity primary key,
    value double precision not null,
    raining boolean not null,
    measured_at timestamp without time zone not null,
    sensor_id integer not null,
    constraint fk_measurements_sensor foreign key (sensor_id) references sensors (id)
);

create index idx_measurements_sensor_id on measurements (sensor_id);
